# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4cb7056eb7bbf75789acb492d8e45c67088bfaf309fcd15ba51117941605942d9f4ee4eb9f98ce18a00dc1c5729eadee9fd74517db51c618944792891d37b13

test:
  secret_key_base: 802acf3be296808f08ffe01a6025af6c3ecb6387c513f2e890af82b6ca542a34ee08a6d5fe1c948956758e7aa125374c20c198cb2ba3b6ba2d5a5e4a5a0c245a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
